apiVersion: v1
kind: Pod
metadata:
        name: nginx1
        labels:
                app: nginx1
                tier: frontend
spec:
        containers:
                - name: nginx
                  image: nginx

